Controllers/PagosController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria23.Models;
using Microsoft.AspNetCore.Authorization;

namespace Inmobiliaria23.Controllers
{
    public class PagosController : Controller
    {
        private readonly PagoRepositorio rePago;
        private readonly ContratoRepositorio reContrato;
        public PagosController()
        {
            rePago = new PagoRepositorio();
            reContrato = new ContratoRepositorio();
        }
        // GET: Pagos
        [Authorize]
        public ActionResult Index()
        {
            if (TempData.ContainsKey("Mensaje"))
            {
                ViewBag.Mensaje = TempData["Mensaje"];
            }
            var lista = rePago.GetPagos();
            return View(lista);
        }

        [Authorize]
        public ActionResult Contrato(int id)
        {
            var lista = rePago.PagosPorContrato(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Contrato = id;
            if (lista.Count() != 0)
            {
                ViewBag.Mensaje = "Cupones del contrato: " + lista[0].contrato.ToString();
            }
            return View("Index", lista);
        }


        // GET: Pagos/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var deuda = rePago.ObtenerDeuda(id);
            ViewBag.Deuda = deuda;
            var lista = rePago.GetPago(id);
            return View(lista);
        }

        [Authorize]
        // GET: Pagos/Create
        public ActionResult Create(int id)
        {
            try
            {
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                if (id == 0)
                {
                    ViewBag.Contratos = reContrato.GetContratos();
                }
                else
                {
                    ViewBag.Contrato = reContrato.GetContrato(id);
                }

                return View();
            }
            catch (System.Exception)
            {

                throw;
            }
        }

        [Authorize]
        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago collection)
        {
            Pago pago = new Pago();
            try
            {
                if (collection.FechaPagado == null)
                {
                    TempData["Mensaje"] = "Debe ingresar la fecha de pago";
                    return RedirectToAction(nameof(Create));
                }
                if (collection.Importe == null)
                {
                    TempData["Mensaje"] = "Debe ingresar un importe mayor a cero";
                    return RedirectToAction(nameof(Create));
                }
                if (collection.Mes == 0)
                {
                    TempData["Mensaje"] = "Debe ingresar N° de cuota";
                    return RedirectToAction(nameof(Create));
                }
                pago.FechaPagado = collection.FechaPagado;
                pago.Importe = collection.Importe;
                pago.ContratoId = (collection.ContratoId == 0) ? collection.Id : collection.ContratoId;
                pago.Mes = collection.Mes;
                if (rePago.Alta(pago) > 0)
                {
                    TempData["Mensaje"] = "Datos guardados correctamente";
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            var lista = rePago.GetPago(id);
            return View(lista);
        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Pago collection)
        {
            Pago pago = new Pago();
            try
            {
                // TODO: Add update logic here
                if (collection.FechaPagado == null)
                {
                    TempData["Mensaje"] = "Debe ingresar la fecha de pago";
                    return RedirectToAction(nameof(Edit), new { id = collection.Id });
                }
                if (collection.Importe <= 0)
                {
                    TempData["Mensaje"] = "Debe ingresar un importe mayor a cero";
                    return RedirectToAction(nameof(Edit), new { id = collection.Id });
                }
                pago = rePago.GetPago(collection.Id);
                pago.FechaPagado = collection.FechaPagado;
                pago.Importe = collection.Importe;
                if (rePago.Modificacion(pago) > 0)
                {
                    TempData["Mensaje"] = "Datos guardados correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Delete/5
        [Authorize(Policy = "Admin")]
        public ActionResult Delete(int id)
        {
            var lista = rePago.GetPago(id);
            return View(lista);
        }

        // POST: Pagos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public ActionResult Eliminar(int id)
        {
            try
            {
                // TODO: Add delete logic here
                if (rePago.Baja(id) > 0)
                {
                    TempData["Mensaje"] = "Datos eliminados correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria23.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;

namespace Inmobiliaria23.Controllers
{
public class UsuariosController : Controller
{
        private readonly UsuarioRepositorio repositorioUsuario;
        private readonly IWebHostEnvironment environment;
        private readonly IConfiguration configuration;

        public UsuariosController(IWebHostEnvironment environment, IConfiguration configuration)
        {
            repositorioUsuario = new UsuarioRepositorio();
            this.environment = environment;
            this.configuration = configuration;
        }

        
        // GET: Usuarios
       [Authorize(Policy = "Admin")]
        public ActionResult Index()
        {
             var usuario = repositorioUsuario.GetUsuarios();
            try
            {
                if (TempData.ContainsKey("Id"))
                    ViewBag.Mensaje = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
				    ViewBag.Mensaje = TempData["Mensaje"];
               
                return View(usuario);
            }
            catch (Exception)
            {

                return View();
            }

        }


        // GET: Usuarios/Details/5
       [Authorize(Policy = "Admin")]
        public ActionResult Details(int id)
        {
            return View();
        }


        // GET: Usuarios/Create
       [Authorize(Policy = "Admin")]
        public ActionResult Create()
        {
           ViewBag.Roles = Usuario.ObtenerRoles();
            return View();
        }

        // POST: Usuarios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
       [Authorize(Policy = "Admin")]
        public ActionResult Create(Usuario u)
        {
            try
            {
                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                                password: u.Clave,
                                salt: System.Text.Encoding.ASCII.GetBytes("Salt"),
                                prf: KeyDerivationPrf.HMACSHA1,
                                iterationCount: 1000,
                                numBytesRequested: 256 / 8));
                u.Clave = hashed;
                u.Rol = User.IsInRole("Admin") ? u.Rol : (int)enRoles.Empleado;
                int res = repositorioUsuario.Alta(u);
                if (u.AvatarFile != null && u.Id > 0)
                {
                    string path = @"wwwroot\Uploads";
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    
                    var nbreRnd = Guid.NewGuid();
                    string fileName = "avatar_" + u.Id + nbreRnd + Path.GetExtension(u.AvatarFile.FileName);
                    string pathCompleto = Path.Combine(path, fileName);
                    u.Avatar = Path.Combine("/Uploads", fileName);                     
                    using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
                    {
                        u.AvatarFile.CopyTo(stream);
                    }
                    repositorioUsuario.Modificacion(u);
                }
                if (res > 0)
                {
                    TempData["Mensaje"] = "Usuario creado correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ViewBag.Roles = Usuario.ObtenerRoles();
                return View();
            }
        }

        // GET: Usuarios/Edit/5
       [Authorize]
        public ActionResult Perfil()
        {
            // if (TempData.ContainsKey("Id"))
            //     ViewBag.Id = TempData["Id"];
            // if (TempData.ContainsKey("Mensaje"))
            //     ViewBag.Mensaje = TempData["Mensaje"];
            ViewData["Title"] = "Mi perfil";
            var u = repositorioUsuario.ObtenerPorEmail(User.Identity.Name);
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View("Perfil", u);
        }

        // GET: Usuarios/Edit/5
       [Authorize(Policy = "Admin")]
        public ActionResult Edit(int id)
        {
            ViewData["Title"] = "Editar usuario";
            var u = repositorioUsuario.GetUsuario(id);
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View(u);
        }

        // POST: Usuarios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(int id, Usuario user)
        {
            Usuario u = new Usuario();
            try
            {
                u = repositorioUsuario.GetUsuario(id);
                u.Nombre = user.Nombre;
                u.Apellido = user.Apellido;
                var cambiaMail = (user.Email != u.Email) ? true : false;
                u.Email = user.Email;
                u.Rol = user.Rol;
                if (repositorioUsuario.Modificacion(u) > 0 && cambiaMail)
                {
                    var identity = (ClaimsIdentity)User.Identity;
                    identity.RemoveClaim(identity.FindFirst(ClaimTypes.Name));
                    identity.AddClaim(new Claim(ClaimTypes.Name, user.Email));
                    await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(identity));
                }

                if (user.AvatarFile != null && u.Id > 0)
                {
                    var ruta = @"wwwroot" + u.Avatar;
                    if (System.IO.File.Exists(ruta))
                    {
                        System.IO.File.Delete(ruta);
                    }
                    var nbreRnd = Guid.NewGuid();
                    string path = @"wwwroot\Uploads";
                    string fileName = "avatar_" + u.Id + nbreRnd + Path.GetExtension(user.AvatarFile.FileName);
                    string pathCompleto = Path.Combine(path, fileName);
                    u.Avatar = @"/Uploads/" + fileName;
                    using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
                    {
                        user.AvatarFile.CopyTo(stream);
                    }
                    repositorioUsuario.Modificacion(u);
                }

                if (user.Clave != null && User.IsInRole("Admin"))
                {
                    string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                                password: user.Clave,
                                salt: System.Text.Encoding.ASCII.GetBytes("Salt"),
                                prf: KeyDerivationPrf.HMACSHA1,
                                iterationCount: 1000,
                                numBytesRequested: 256 / 8));
                    u.Clave = hashed;
                    repositorioUsuario.Modificacion(u);
                }

                TempData["Mensaje"] = "Datos guardados correctamente";
               if (!User.IsInRole("Admin")) { return RedirectToAction(nameof(Perfil)); }
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CambiarClave(int id, String claveNueva, String clave, String confirmarNueva)
        {
            Usuario u = new Usuario();
            string hashed;
            try
            {
                if (clave == null)
                {
                    TempData["Mensaje"] = "La contraseña no puede estar vacía";
                    return RedirectToAction(nameof(Perfil));
                }

                u = repositorioUsuario.GetUsuario(id);
                if (claveNueva == confirmarNueva)
                {
                    hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                                                    password: claveNueva,
                                                    salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                                                    prf: KeyDerivationPrf.HMACSHA1,
                                                    iterationCount: 1000,
                                                    numBytesRequested: 256 / 8));
                    claveNueva = hashed;
                }
                else
                {
                    TempData["Mensaje"] = "Las contraseñas no coinciden";
                    return RedirectToAction(nameof(Perfil));
                }

                hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                                                 password: clave,
                                                 salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                                                 prf: KeyDerivationPrf.HMACSHA1,
                                                 iterationCount: 1000,
                                                 numBytesRequested: 256 / 8));
                clave = hashed;

                if (clave == u.Clave)
                {
                    u.Clave = claveNueva;
                    repositorioUsuario.Modificacion(u);
                    TempData["Mensaje"] = "Contraseña actualizada";
                }
                else
                {
                    TempData["Mensaje"] = "Contraseña actual invalida";
                    return RedirectToAction(nameof(Perfil));
                }

                return RedirectToAction(nameof(Perfil));
            }
            catch (System.Exception)
            {

                throw;
            }
        }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria -</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inmobiliaria23.styles.css" asp-append-version="true" />

    @* <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" /> *@
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css" />

    <link rel="icon" href="~/img/favicon.png" type="image/x-icon" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" defer></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  bg-dark  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <div class="navbar-text-container"></div> *@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>Inmobiliaria JE</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Propietarios"
                                asp-action="Index">Propietarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Inquilinos"
                                asp-action="Index">Inquilinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Inmuebles"
                                asp-action="Index">Inmuebles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contratos"
                                asp-action="Index">Contratos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Pagos"
                                asp-action="Index">Pagos</a>
                        </li>
                        @if (User.IsInRole("SuperAdmin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Usuarios"
                                        asp-action="Index">Usuarios</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item center-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Usuarios" asp-action="Perfil">Mi
                                        Perfil</a>
                                </li>
                            }
                            <li class="nav-item center-item">
                                <a class="nav-link text-light" href="/salir">Deslogear</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="">
                @if (ViewBag.Id != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>¡Éxito!</strong> Fue dada de alta id: @ViewBag.Id
                       
                    </div>
                }
                else if (ViewBag.Mensaje != null)
                {//cartel general
                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                        <strong>Información:</strong> @ViewBag.Mensaje
                        
                    </div>
                }
                else if (ViewBag.MensajeError != null)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>¡Error!</strong> @ViewBag.MensajeError
                       
                    </div>
                }
                else if (ViewBag.Error != null)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>¡Error!</strong> @ViewBag.Error
                        
                    </div>
                }
                else if (!String.IsNullOrWhiteSpace(ViewBag.Error))
                {//ocurrió un error
                    <environment names="Development">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>¡Error!</strong> Ocurrió: @ViewBag.Error
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button"
                                aria-expanded="false"><span class="lnr lnr-plus-circle"></span></a>
                            <div class="collapse multi-collapse" id="multiCollapseExample1">
                                @ViewBag.StackTrace
                            </div>
                        </div>
                    </environment>
                }
                <div class="m-1 p-1">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy; @DateTime.Today.Year - Inmobiliaria - &middot; <a href="#">Privacy</a>
                &middot; <a href="#">Terms</a> <a class="float-right" href="#">Volver arriba</a></span>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/53d3fcf520.js" crossorigin="anonymous"></script>


    <script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

</body>

</html>

Views/Shared/_LoginModal.cshtml
<div class="modal" tabindex="-1" role="dialog" id="modal_login">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<partial name="_Login.cshtml" />
			</div>
		</div>
	</div>
</div>
<script>
	function fs() {
		console.log("Modal cargado");
	}
</script>

Views/Shared/_ScriptsPartial.cshtml
<script src="~/lib/jquery/jquery.js"></script>
<script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>