Models/Propietario.cs
using System.ComponentModel.DataAnnotations;

namespace Inmobiliaria23.Models;

public class Propietario
{
    [Key]
    [Display(Name ="Id")]
    public int Id { get; set; }
    [Required]
    public string Nombre { get; set;}="";
    [Required]
    public string Apellido { get; set;}="";
    [Required]
    public string DNI { get; set;}="";

    [Required]
    [Display(Name ="Teléfono")]
    public string Telefono { get; set;}="";

    [Required,EmailAddress]
    public string Email { get; set; }="";

    public ICollection<Inmueble> Inmuebles { get; set; }
    

public Propietario(string Nombre, string Apellido, string DNI, string Telefono, string Email)
    {
        this.Nombre = Nombre;
        this.Apellido = Apellido;
        this.DNI = DNI;
        this.Telefono = Telefono;
        this.Email = Email;
    }

    public Propietario() { }

    public override string ToString()
    {     
        return $"{Nombre} {Apellido} ({DNI})";
    }
}

Controllers/InmueblesController.cs
using Microsoft.AspNetCore.Authorization;
using Inmobiliaria23.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inmobiliaria23.Controllers
{
    public class InmueblesController : Controller
    {
        // GET: Inmuebles
        private readonly InmuebleRepositorio inmuebleRepositorio;
        private readonly PropietarioRepositorio propietarioRepositorio;
        public InmueblesController()
        {
            inmuebleRepositorio = new InmuebleRepositorio();
            propietarioRepositorio = new PropietarioRepositorio();
        }
        // GET: Inmuebles
        [Authorize]
        public ActionResult Index()
        {
            var lista = inmuebleRepositorio.GetInmuebles();
			if (TempData.ContainsKey("Id"))
				ViewBag.Id = TempData["Id"];
			if (TempData.ContainsKey("Mensaje"))
				ViewBag.Mensaje = TempData["Mensaje"];
			return View(lista);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Disponibles(DateTime fechaInicio, DateTime fechaFin)
        {
            try
            {
                var FechaInicio = fechaInicio;
                var FechaFin = fechaFin;

                var lista = inmuebleRepositorio.GetInmueblesDisponiblesPorFechas(FechaInicio, FechaFin);

                if (TempData.ContainsKey("Id"))
                    ViewBag.Id = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                if (lista.Count != 0)
                {
                    ViewBag.Mensaje = "Inmuebles disponibles entre: " + FechaInicio.ToString("dd/MM/yyyy") + " y " + FechaFin.ToString("dd/MM/yyyy");
                }
                return View("Index", lista);
            }
            catch (System.Exception)
            {

                throw;
            }
        }

        [Authorize]
         public ActionResult Propietario(int id)
        {
            var lista = inmuebleRepositorio.BuscarPorPropietario(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Propietario = id;
            if (lista.Count != 0)
            {
                ViewBag.Mensaje = "Inmuebles del propietario: " + lista[0].Propietario?.Nombre + " " + lista[0].Propietario?.Apellido;
            }
            return View("Index", lista);
        }

        // GET: Inmuebles/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            ViewBag.Propietarios = propietarioRepositorio.GetPropietarios();
            var inmueble = inmuebleRepositorio.GetInmueble(id);
            return View(inmueble);
        }

        // GET: Inmuebles/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            try
            {
                if (TempData.ContainsKey("Mensaje")) {
                    ViewBag.Mensaje = TempData["Mensaje"];
                }
                ViewBag.Propietarios = propietarioRepositorio.GetPropietarios();
                ViewBag.Propietario = id;

                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: Inmuebles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Inmueble inmueble)
        {
            try
            {
                if (inmueble.Direccion == null || inmueble.Ambientes == null
                || inmueble.Superficie == null || inmueble.Latitud == null
                || inmueble.Precio == null || inmueble.Longitud == null)
                {
                    TempData["Mensaje"] = "Debe llenar todos los campos";
                    return RedirectToAction(nameof(Create));
                }
                ViewBag.Propietarios = propietarioRepositorio.GetPropietarios();
                if (inmuebleRepositorio.Alta(inmueble) > 0)
                {
                    TempData["Mensaje"] = "Inmueble creado con exito! Id: " + inmueble.Id;
                }
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(inmueble);
            }
        }

        // GET: Inmuebles/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var inmueble = inmuebleRepositorio.GetInmueble(id);
            ViewBag.Propietarios = propietarioRepositorio.GetPropietarios();
            ViewBag.PropietarioActual = propietarioRepositorio.GetPropietario(inmueble.PropietarioId);
            return View(inmueble);
        }

        // POST: Inmuebles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, Inmueble collection)
        {
            Inmueble inmueble = new Inmueble();

            try
            {
                inmueble = inmuebleRepositorio.GetInmueble(id);
                inmueble.Ambientes = collection.Ambientes;
                inmueble.Direccion = collection.Direccion;
                inmueble.Id = collection.Id;
                inmueble.Latitud = collection.Latitud;
                inmueble.PropietarioId = collection.PropietarioId;
                inmueble.Longitud = collection.Longitud;
                inmueble.Superficie = collection.Superficie;
                inmueble.Tipo = collection.Tipo;
                inmueble.Precio = collection.Precio;
                inmueble.Estado = collection.Estado;
                if (inmuebleRepositorio.Modificacion(inmueble) > 0)
                {
                    TempData["Mensaje"] = "Datos guardados correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Inmuebles/Delete/5
        [Authorize(Policy = "Admin")]
        public ActionResult Delete(int id)
        {
            var inmueble = inmuebleRepositorio.GetInmueble(id);
            return View(inmueble);
        }

        // POST: Inmuebles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                if (inmuebleRepositorio.Baja(id) > 0)
                {
                    TempData["Mensaje"] = "Eliminación realizada correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PropietariosController.cs
using Microsoft.AspNetCore.Authorization;
using Inmobiliaria23.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inmobiliaria23.Controllers
{
    public class PropietariosController : Controller
    {
        private readonly PropietarioRepositorio repositorio;
        public PropietariosController()
        {
            repositorio = new PropietarioRepositorio();
        }
        // GET: Propietarios
   [Authorize]
        public ActionResult Index()
        {
            var lista = repositorio.GetPropietarios();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
             if (TempData.ContainsKey("MensajeError"))
                ViewBag.Error = TempData["MensajeError"];
            return View(lista);
            // List<Propietario> propietarios = repositorio.GetPropietarios();
            // return View(propietarios);
        }

        // GET: Propietarios/Details/5
     [Authorize]
        public ActionResult Details(int id)
        {
            var propietario = repositorio.GetPropietario(id);
            // Cargar explícitamente los inmuebles relacionados
            propietario.Inmuebles = repositorio.ObtenerInmueblesDelPropietario(id);
            return View(propietario);
        }


        // GET: Propietarios/Create
       [HttpGet]
       [Authorize]
        public ActionResult Create()
        {
            if (TempData.ContainsKey("Mensaje"))
                {
                    ViewBag.Mensaje = TempData["Mensaje"];
                }
                else if (TempData.ContainsKey("Error"))
                {
                    ViewBag.Error = TempData["Error"];
                }
            return View();
        }

        // POST: Propietarios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]   
        [Authorize]
        public ActionResult Create(Propietario propietario)
        {
            try
            {                
               // if (ModelState.IsValid) {
                if (propietario.Nombre != null || propietario.Apellido != null || propietario.DNI != null
                || propietario.Telefono != null || propietario.Email != null)
                {
                    repositorio.Alta(propietario);
                    TempData["Id"] = propietario.Id;
                    return RedirectToAction(nameof(Index));
                }
                else {
                    TempData["MensajeError"] = "Debe completar todos los campos!";
                return RedirectToAction(nameof(Create));
                }
            }
            catch
            {
                TempData["MensajeError"] = "No se pudo CREAR el propietario.";
                return RedirectToAction(nameof(Index));
                throw;
            }
        }

        // GET: Propietarios/Edit/5
       [HttpGet]
       [Authorize]
        public ActionResult Edit(int id)
        {
            var prop = repositorio.GetPropietario(id);
            return View(prop);
        }


        // POST: Propietarios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        
        public ActionResult Edit(int id, Propietario collection) //, Propietario collection
        {
            Propietario p = new Propietario();
            try
            {
                p = repositorio.GetPropietario(id);
                p.Nombre = collection.Nombre;
                p.Apellido = collection.Apellido;
                p.DNI = collection.DNI;
                p.Telefono = collection.Telefono;
                p.Email = collection.Email;
                if (repositorio.Modificacion(p) > 0)
                {
                    TempData["Mensaje"] = "Datos guardados correctamente";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception )
            {//poner breakpoints para detectar errores
            TempData["MensajeError"] = "No se puede EDITAR el propietario.";
                return RedirectToAction(nameof(Index));
                throw;
            }
        }

        // GET: Propietarios/Delete/5
       [Authorize(Policy = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                var prop = repositorio.GetPropietario(id);
                return View(prop);
                
            }
            catch (Exception)
            {
                TempData["MensajeError"] = "No se puede eliminar el propietario.";
                return RedirectToAction(nameof(Index));
                throw;
            }
            
        }

        // POST: Propietarios/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]  
        [Authorize(Policy = "Admin")]     
        public ActionResult Delete(int id, IFormCollection collection)

        {
            try
            {
                repositorio.Baja(id);
                
                    TempData["Mensaje"] = "Se eliminó correctamente";
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                //throw; //return View();
                TempData["MensajeError"] = "No se puede eliminar el propietario debido a inmuebles vinculados.";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Views/Propietarios/Create.cshtml
@model Inmobiliaria23.Models.Propietario

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Propietario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" type="text" name="DNI" class="form-control"/>
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" type="text" name="Telefono" class="form-control"/>
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

Views/Propietarios/Delete.cshtml
@model Inmobiliaria23.Models.Propietario

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Esta usted seguro de eliminar este propietario?</h3>
<div>
    <h4>Propietario</h4>
    <hr />
    @* <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-success btn-block">  Volver  </a>
    </form>

</div>

Views/Propietarios/Details.cshtml
@model Inmobiliaria23.Models.Propietario

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Propietario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <h4>Inmuebles</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Dirección</th>
                <th>Precio</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var inmueble in Model.Inmuebles.ToList())
            {
                <tr>
                    <td>@inmueble.Direccion</td>
                    <td>@inmueble.Precio.Value.ToString("C")</td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })|
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

Views/Propietarios/Edit.cshtml
@model Inmobiliaria23.Models.Propietario

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Propietario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control"  name="Nombre" value=@Model.Nombre required/>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" name="Apellido" value=@Model.Apellido required/>
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input type="number" name="DNI" class="form-control" id="DNI" value=@Model.DNI required>
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input type="number" name="Telefono" class="form-control" id="Telefono" value=@Model.Telefono>
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" name="Email" value=@Model.Email />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Propietarios/Index.cshtml
@model IEnumerable<Inmobiliaria23.Models.Propietario>

@{
    ViewData["Title"] = "Propietarios";
}

<h1>Propietarios</h1>

<a asp-action="Create" class="btn btn-success"><i class="fa-solid fa-address-card style="color: #000000;"></i>   Crear nuevo</a>
<br>
<br>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            
            <th>
                Accion
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
         
            <td>
                @Html.ActionLink(" ", "Edit", new { id=item.Id }, new { @class = "fas fa-edit btn btn-primary rounded-circle", title = "Editar"  })  
                @Html.ActionLink(" ", "Details", new { id=item.Id  }, new { @class = "fa-regular fa-file-lines btn btn-secondary rounded-circle", title = "Detalle"  }) 
                @if(User.IsInRole("Admin") || User.IsInRole("SuperAdmin" )){ @Html.ActionLink(" ", "Delete", new { id=item.Id  }, new { @class = "fa-solid fa-trash-can btn btn-danger rounded-circle", title = "Eliminar"  })}
                @Html.ActionLink(" ", "Propietario", "Inmuebles", new { id= item.Id }, new { @class="lnr lnr-apartment btn btn-warning rounded-circle", title = "Propiedades" })
            </td>
        </tr>
}
    </tbody>
</table>